import { createContext, useContext, useState, useEffect } from "react";

const translations = {
  en: {
    common: { save: "Save", cancel: "Cancel", delete: "Delete", edit: "Edit", create: "Create", update: "Update", close: "Close", confirm: "Confirm", search: "Search", filter: "Filter", reset: "Reset", loading: "Loading...", noData: "No data", actions: "Actions", status: "Status", active: "Active", inactive: "Inactive", yes: "Yes", no: "No", back: "Back", next: "Next", previous: "Previous", finish: "Finish", logout: "Logout" },
    auth: { login: "Login", logout: "Logout", welcome: "Welcome" },
    nav: { dashboard: "Dashboard", missions: "Missions", calendar: "Calendar", messages: "Messages", notifications: "Notifications", reports: "Reports", performance: "SOC Performance", countries: "Countries", zones: "SRM Zones", users: "Users", tour: "Virtual Tour & FAQ" },
    dashboard: { title: "Dashboard", welcome: "Welcome, {name}", newMission: "New Mission", filters: "Filters", allStatuses: "All Statuses", allCountries: "All Countries", dateFrom: "Start Date", dateTo: "End Date", resetFilters: "Reset", stats: { activeMissions: "Active Missions", plannedMissions: "Planned Missions", completedMissions: "Completed Missions", potentialDelays: "Potential Delays", totalSegments: "Total Segments" }, recentMissions: "Recent Missions", recentSegmentsMap: "Recent Segments Map", activeCountries: "Active Countries", quickActions: "Quick Actions", allMissions: "All Missions", userManagement: "User Management", noMissions: "No missions yet", createMission: "Create a mission", zones: "zones", missions: "missions", manageCountries: "Manage Countries", myCountry: "My Country", manageZones: "Manage SRM Zones", myZones: "My SRM Zones" },
    missions: { title: "Missions", newMission: "New Mission", missionDetails: "Mission Details", allMissions: "All Missions", planned: "Planned", inProgress: "In Progress", completed: "Completed", cancelled: "Cancelled", status: "Status", agency: "Agency", country: "Country", criticality: "Criticality", startDate: "Start Date", endDate: "End Date", createdDate: "Created", segments: "{count} segment(s)", noMissions: "No missions found", createFirst: "Create the first mission", object: "Objective", description: "Description", socAssistant: "SOC Assistant", ochaNotified: "OCHA Notified", addSegment: "Add Segment", viewDetails: "View Details", documents: "Documents", found: "{count} mission(s) found" },
    calendar: { title: "Mission Calendar", missions: "{count} mission(s) displayed", allStatuses: "All Statuses", allCountries: "All Countries", allZones: "All Zones", legend: "Legend", dragDropTip: "You can drag and drop missions to modify their dates", month: "Month", week: "Week", day: "Day", agenda: "Agenda", today: "Today", previous: "Previous", next: "Next", allDay: "All day", date: "Date", time: "Time", event: "Event", noEventsInRange: "No missions in this period", showMore: "+ {total} mission(s)" },
    segments: { title: "Segments", newSegment: "New Segment", segmentDetails: "Segment Details", number: "Segment {number}", departure: "Departure", arrival: "Arrival", departureTime: "Departure Time", arrivalTime: "Arrival Time", transport: "Transport", team: "Team", vehicles: "Vehicles", road: "Road", air: "Air", both: "Mixed", endOfMission: "End of Mission", route: "Route", distance: "Distance", duration: "Duration", noSegments: "No segments", createFirst: "Create the first segment", members: "{count} member(s)" },
    reports: { title: "Reports", generate: "Generate Report", missions: "Missions Report", zones: "SRM Zones Report", vehicles: "Vehicles Report", teams: "Teams Report", period: "Period", download: "Download", statistics: "Statistics" },
    performance: { title: "SOC Performance", overview: "Overview", missionsCreated: "Missions Created", missionsCompleted: "Missions Completed", segmentsTracked: "Segments Tracked", reportsSubmitted: "Reports Submitted", avgResponseTime: "Avg Response Time", qualityScore: "Quality Score", topPerformers: "Top Performers", subtitle: "Performance tracking and evaluation", assistants: "SOC Assistants", completed: "Completed", segments: "Tracked Segments", reports: "Reports", averageScore: "Avg Score", detailByAssistant: "Detail by SOC Assistant", countryZones: "Country / Zones", completionRate: "Rate", score: "Score", noAssistantsFound: "No SOC assistant found", topPerformer: "Top Performer", mostActive: "Most Active", mostReports: "Most Reports", completedMissions: "completed missions", missions: "missions", trackedSegments: "tracked segments", submittedReports: "reports", rate: "Rate" },
    reports: { title: "Reports", generate: "Generate Report", missions: "Missions Report", zones: "SRM Zones Report", vehicles: "Vehicles Report", teams: "Teams Report", period: "Period", download: "Download", statistics: "Statistics", subtitle: "Generate detailed activity reports", exportPDF: "Export PDF", filters: "Filters", weekly: "Weekly", monthly: "Monthly", custom: "Custom", dateFrom: "Start Date", dateTo: "End Date", country: "Country", allCountries: "All Countries", srmZone: "SRM Zone", allZones: "All Zones", totalMissions: "Total Missions", completedMissions: "Completed", inProgress: "In Progress", totalDistance: "Total Distance", kilometers: "kilometers", byStatus: "By Status", byAgency: "By Agency", resources: "Resources", teams: "Teams" },
    users: { title: "User Management", addUser: "Add User", editUser: "Edit User", email: "Email", fullName: "Full Name", role: "Role", assignedCountry: "Assigned Country", assignedZones: "Assigned Zones", isActive: "Active", noUsers: "No users", deleteConfirm: "Delete this profile?", deleteMessage: "Are you sure you want to delete {name}'s profile? This action is irreversible.", assignRolesPermissions: "Assign roles and access zones", user: "User", undssRole: "UNDSS Role", actions: "Actions", selectRole: "Select a role", selectCountry: "Select a country", zonesForCountry: "Country for zones", assignedSRMZones: "Assigned SRM Zones", noZonesInCountry: "No zones in this country", onlyAssignZonesInYourCountry: "You can only assign zones from your country", country: "Country", firstName: "First Name" },
    notifications: { title: "Notifications", markAllRead: "Mark all as read", noNotifications: "No notifications", types: { deadline: "Deadline", criticalSegment: "Critical Segment", statusUpdate: "Status Update", assignment: "Assignment", info: "Information" }, unread: "{count} unread", allRead: "All read", deleteRead: "Delete read", viewDetails: "View details →", priority: { low: "Low", medium: "Medium", high: "High", urgent: "Urgent" }, all: "All", unreadTab: "Unread", deadlines: "Deadlines", critical: "Critical", statuses: "Statuses", assignments: "Assignments" },
    notifications: { title: "Notifications", markAllRead: "Mark all as read", noNotifications: "No notifications", types: { deadline: "Deadline", criticalSegment: "Critical Segment", statusUpdate: "Status Update", assignment: "Assignment", info: "Information" } },
    chat: { title: "Messages", newConversation: "New Conversation", direct: "Direct", group: "Group", typeMessage: "Type a message...", send: "Send", noConversations: "No conversations", searchUsers: "Search users..." },
    calendar: { title: "Calendar", month: "Month", week: "Week", day: "Day", agenda: "Agenda", today: "Today", noEvents: "No events" },
    tour: { title: "Help & Virtual Tour", start: "Start Guided Tour", faq: "Frequently Asked Questions (FAQ)", searchFaq: "Search FAQ...", noResults: "No results found", subtitle: "Discover how to use all the application features", tourTitle: "Interactive Virtual Tour", tourDescription: "Follow a step-by-step guided tour to discover all the application features. The tour guides you through different sections and explains their usage.", additionalTips: "Additional Tips", tip1: "Use the FAQ search to quickly find an answer", tip2: "You can restart the guided tour anytime from this page", tip3: "Real-time notifications inform you of all important changes", tip4: "The calendar allows you to modify dates by drag and drop", tip5: "Uploaded documents are accessible only to authorized users", step: "Step", of: "of", previous: "Previous", next: "Next", finish: "Finish", exitTourQuestion: "Are you sure you want to exit the guided tour?", startButton: "Start Guided Tour" },
    countries: { title: "Country Management", subtitle: "Configure countries and their SRM zones", addCountry: "Add Country", editCountry: "Edit Country", country: "Country", code: "Code", srmZones: "SRM Zones", status: "Status", actions: "Actions", noCountries: "No countries configured", createFirst: "Add your first country", countryName: "Country Name", isoCode: "ISO Code", countryActive: "Country Active", zones: "zones", newZone: "New Zone" },
    zones: { title: "SRM Zones", subtitle: "Security risk management zones", newZone: "New Zone", editZone: "Edit Zone", createZone: "Create SRM Zone", zone: "Zone", country: "Country", riskLevel: "Risk Level", status: "Status", actions: "Actions", noZones: "No SRM zones configured", createFirst: "Create a zone", zoneName: "Zone Name", description: "Description", zoneActive: "Zone Active", filterByCountry: "Filter by country", allCountries: "All Countries", selectCountry: "Select a country", riskLevels: { low: "Low", moderate: "Moderate", high: "High", very_high: "Very High", extreme: "Extreme" } },
    reportMissions: { totalMissions: "Total Missions", completed: "Completed", inProgress: "In Progress", totalDistance: "Total Distance", kilometers: "kilometers", byStatus: "Distribution by Status", byAgency: "Missions by Agency", agencyDetail: "Detail by Agency", agency: "Agency", total: "Total", rate: "Rate", noData: "No data" },
    roles: { super_admin: "Super Admin", csa: "CSA", dsa: "DSA", fsco: "FSCO", fsa: "FSA", assistant_soc: "Assistant SOC", undefined: "Not defined" },
    criticality: { PC1: "PC1 - Critical", PC2: "PC2 - High", PC3: "PC3 - Medium", PC4: "PC4 - Low" },
    transport: { road: "Road", air: "Air", both: "Mixed" },
    status: { planned: "Planned", in_progress: "In Progress", completed: "Completed", cancelled: "Cancelled" },
    errors: { generic: "An error occurred", unauthorized: "Unauthorized", notFound: "Not found", required: "This field is required" },
    success: { saved: "Saved successfully", created: "Created successfully", updated: "Updated successfully", deleted: "Deleted successfully", profileCreated: "Profile created", profileUpdated: "Profile updated", profileDeleted: "Profile deleted" },
    accessDenied: { title: "Access Denied", contactAdmin: "Please contact your Admin to be assigned your areas of responsibility.", accountCreated: "Your account has been created but no areas of responsibility have been assigned yet. Access to the application will be activated once your areas are assigned.", contactZoneManager: "Contact your zone manager", logout: "Logout", welcomeTitle: "Welcome!", selectCountry: "Select your country of assignment to continue", chooseCountry: "Choose a country", afterSelection: "After your selection, the administrators of this country will be notified and can activate your account.", sendRequest: "Send request", requestSubmitted: "Request sent", adminNotified: "Administrators have been notified of your request. You will receive an email when your account is activated.", selectedCountry: "Selected country", newUserRequest: "New activation request", newUserMessage: "{name} requests activation for country: {country}", requestSent: "Request sent successfully" }
  },
  fr: {
    common: { save: "Enregistrer", cancel: "Annuler", delete: "Supprimer", edit: "Modifier", create: "Créer", update: "Mettre à jour", close: "Fermer", confirm: "Confirmer", search: "Rechercher", filter: "Filtrer", reset: "Réinitialiser", loading: "Chargement...", noData: "Aucune donnée", actions: "Actions", status: "Statut", active: "Actif", inactive: "Inactif", yes: "Oui", no: "Non", back: "Retour", next: "Suivant", previous: "Précédent", finish: "Terminer", logout: "Déconnexion" },
    auth: { login: "Connexion", logout: "Déconnexion", welcome: "Bienvenue" },
    nav: { dashboard: "Tableau de bord", missions: "Missions", calendar: "Calendrier", messages: "Messages", notifications: "Notifications", reports: "Rapports", performance: "Performance SOC", countries: "Pays", zones: "Zones SRM", users: "Utilisateurs", tour: "Visite virtuelle & FAQ" },
    dashboard: { title: "Tableau de Bord", welcome: "Bienvenue, {name}", newMission: "Nouvelle Mission", filters: "Filtres", allStatuses: "Tous les statuts", allCountries: "Tous les pays", dateFrom: "Date début", dateTo: "Date fin", resetFilters: "Réinitialiser", stats: { activeMissions: "Missions en cours", plannedMissions: "Missions planifiées", completedMissions: "Missions terminées", potentialDelays: "Retards potentiels", totalSegments: "Total segments" }, recentMissions: "Missions récentes", recentSegmentsMap: "Carte des segments récents", activeCountries: "Pays actifs", quickActions: "Actions rapides", allMissions: "Toutes les missions", userManagement: "Gestion des utilisateurs", noMissions: "Aucune mission pour le moment", createMission: "Créer une mission", zones: "zones", missions: "missions", manageCountries: "Gérer les pays", myCountry: "Mon pays", manageZones: "Gérer les zones SRM", myZones: "Mes zones SRM" },
    missions: { title: "Missions", newMission: "Nouvelle Mission", missionDetails: "Détails de la mission", allMissions: "Toutes les missions", planned: "Planifiées", inProgress: "En cours", completed: "Terminées", cancelled: "Annulées", status: "Statut", agency: "Agence", country: "Pays", criticality: "Criticité", startDate: "Date début", endDate: "Date fin", createdDate: "Créée le", segments: "{count} segment(s)", noMissions: "Aucune mission trouvée", createFirst: "Créer la première mission", object: "Objet", description: "Description", socAssistant: "Assistant SOC", ochaNotified: "OCHA notifiée", addSegment: "Ajouter un segment", viewDetails: "Voir les détails", documents: "Documents", found: "{count} mission(s) trouvée(s)" },
    calendar: { title: "Calendrier des Missions", missions: "{count} mission(s) affichée(s)", allStatuses: "Tous les statuts", allCountries: "Tous les pays", allZones: "Toutes les zones", legend: "Légende", dragDropTip: "Vous pouvez glisser-déposer les missions pour modifier leurs dates", month: "Mois", week: "Semaine", day: "Jour", agenda: "Agenda", today: "Aujourd'hui", previous: "Précédent", next: "Suivant", allDay: "Journée", date: "Date", time: "Heure", event: "Événement", noEventsInRange: "Aucune mission dans cette période", showMore: "+ {total} mission(s)" },
    segments: { title: "Segments", newSegment: "Nouveau Segment", segmentDetails: "Détails du segment", number: "Segment {number}", departure: "Départ", arrival: "Arrivée", departureTime: "Heure de départ", arrivalTime: "Heure d'arrivée", transport: "Transport", team: "Équipe", vehicles: "Véhicules", road: "Routier", air: "Aérien", both: "Mixte", endOfMission: "Fin de mission", route: "Itinéraire", distance: "Distance", duration: "Durée", noSegments: "Aucun segment", createFirst: "Créer le premier segment", members: "{count} membre(s)" },
    reports: { title: "Rapports", generate: "Générer un rapport", missions: "Rapport missions", zones: "Rapport zones SRM", vehicles: "Rapport véhicules", teams: "Rapport équipes", period: "Période", download: "Télécharger", statistics: "Statistiques" },
    performance: { title: "Performance SOC", overview: "Vue d'ensemble", missionsCreated: "Missions créées", missionsCompleted: "Missions terminées", segmentsTracked: "Segments suivis", reportsSubmitted: "Rapports soumis", avgResponseTime: "Temps de réponse moyen", qualityScore: "Score qualité", topPerformers: "Meilleurs contributeurs", subtitle: "Suivi et évaluation des performances", assistants: "Assistants SOC", completed: "Terminées", segments: "Segments suivis", reports: "Rapports", averageScore: "Score moyen", detailByAssistant: "Détail par Assistant SOC", countryZones: "Pays / Zones", completionRate: "Taux", score: "Score", noAssistantsFound: "Aucun assistant SOC trouvé", topPerformer: "Top Performer", mostActive: "Plus actif", mostReports: "Plus de rapports", completedMissions: "missions terminées", missions: "missions", trackedSegments: "segments suivis", submittedReports: "rapports", rate: "Taux" },
    reports: { title: "Rapports", generate: "Générer un rapport", missions: "Rapport missions", zones: "Rapport zones SRM", vehicles: "Rapport véhicules", teams: "Rapport équipes", period: "Période", download: "Télécharger", statistics: "Statistiques", subtitle: "Générez des rapports d'activités détaillés", exportPDF: "Exporter PDF", filters: "Filtres", weekly: "Hebdomadaire", monthly: "Mensuel", custom: "Personnalisé", dateFrom: "Date début", dateTo: "Date fin", country: "Pays", allCountries: "Tous les pays", srmZone: "Zone SRM", allZones: "Toutes les zones", totalMissions: "Total Missions", completedMissions: "Terminées", inProgress: "En cours", totalDistance: "Distance totale", kilometers: "kilomètres", byStatus: "Répartition par statut", byAgency: "Missions par agence", resources: "Ressources", teams: "Équipes" },
    users: { title: "Gestion des Utilisateurs", addUser: "Ajouter un utilisateur", editUser: "Modifier l'utilisateur", email: "Email", fullName: "Nom complet", role: "Rôle", assignedCountry: "Pays assigné", assignedZones: "Zones assignées", isActive: "Actif", noUsers: "Aucun utilisateur", deleteConfirm: "Supprimer ce profil ?", deleteMessage: "Êtes-vous sûr de vouloir supprimer le profil de {name} ? Cette action est irréversible.", assignRolesPermissions: "Attribuez les rôles et les zones d'accès", user: "Utilisateur", undssRole: "Rôle UNDSS", actions: "Actions", selectRole: "Sélectionner un rôle", selectCountry: "Sélectionner un pays", zonesForCountry: "Pays pour les zones", assignedSRMZones: "Zones SRM assignées", noZonesInCountry: "Aucune zone dans ce pays", onlyAssignZonesInYourCountry: "Vous pouvez uniquement attribuer des zones de votre pays", country: "Pays", firstName: "Prénom Nom" },
    notifications: { title: "Notifications", markAllRead: "Tout marquer comme lu", noNotifications: "Aucune notification", types: { deadline: "Échéance", criticalSegment: "Segment critique", statusUpdate: "Changement de statut", assignment: "Assignation", info: "Information" }, unread: "{count} non lue(s)", allRead: "Toutes lues", deleteRead: "Supprimer lues", viewDetails: "Voir détails →", priority: { low: "Basse", medium: "Moyenne", high: "Haute", urgent: "Urgente" }, all: "Toutes", unreadTab: "Non lues", deadlines: "Échéances", critical: "Critiques", statuses: "Statuts", assignments: "Assignations" },
    notifications: { title: "Notifications", markAllRead: "Tout marquer comme lu", noNotifications: "Aucune notification", types: { deadline: "Échéance", criticalSegment: "Segment critique", statusUpdate: "Changement de statut", assignment: "Assignation", info: "Information" } },
    chat: { title: "Messages", newConversation: "Nouvelle conversation", direct: "Direct", group: "Groupe", typeMessage: "Tapez un message...", send: "Envoyer", noConversations: "Aucune conversation", searchUsers: "Rechercher des utilisateurs..." },
    calendar: { title: "Calendrier", month: "Mois", week: "Semaine", day: "Jour", agenda: "Agenda", today: "Aujourd'hui", noEvents: "Aucun événement" },
    tour: { title: "Aide & Visite guidée", start: "Démarrer la visite guidée", faq: "Questions fréquentes (FAQ)", searchFaq: "Rechercher dans la FAQ...", noResults: "Aucun résultat trouvé", subtitle: "Découvrez comment utiliser toutes les fonctionnalités de l'application", tourTitle: "Visite virtuelle interactive", tourDescription: "Suivez une visite guidée pas à pas pour découvrir toutes les fonctionnalités de l'application. La visite vous accompagne à travers les différentes sections et explique leur utilisation.", additionalTips: "Astuces supplémentaires", tip1: "Utilisez la recherche dans la FAQ pour trouver rapidement une réponse", tip2: "Vous pouvez relancer la visite guidée à tout moment depuis cette page", tip3: "Les notifications en temps réel vous informent de tous les changements importants", tip4: "Le calendrier permet de modifier les dates par glisser-déposer", tip5: "Les documents uploadés sont accessibles uniquement aux utilisateurs autorisés", step: "Étape", of: "sur", previous: "Précédent", next: "Suivant", finish: "Terminer", exitTourQuestion: "Êtes-vous sûr de vouloir quitter la visite guidée ?", startButton: "Démarrer la visite guidée" },
    countries: { title: "Gestion des Pays", subtitle: "Configurez les pays et leurs zones SRM", addCountry: "Ajouter un pays", editCountry: "Modifier le pays", country: "Pays", code: "Code", srmZones: "Zones SRM", status: "Statut", actions: "Actions", noCountries: "Aucun pays configuré", createFirst: "Ajouter votre premier pays", countryName: "Nom du pays", isoCode: "Code ISO", countryActive: "Pays actif", zones: "zones", newZone: "Nouvelle zone" },
    zones: { title: "Zones SRM", subtitle: "Gestion des zones de risque sécuritaire", newZone: "Nouvelle zone", editZone: "Modifier la zone", createZone: "Créer une zone SRM", zone: "Zone", country: "Pays", riskLevel: "Niveau de risque", status: "Statut", actions: "Actions", noZones: "Aucune zone SRM configurée", createFirst: "Créer une zone", zoneName: "Nom de la zone", description: "Description", zoneActive: "Zone active", filterByCountry: "Filtrer par pays", allCountries: "Tous les pays", selectCountry: "Sélectionner un pays", riskLevels: { low: "Faible", moderate: "Modéré", high: "Élevé", very_high: "Très élevé", extreme: "Extrême" } },
    reportMissions: { totalMissions: "Total Missions", completed: "Terminées", inProgress: "En cours", totalDistance: "Distance totale", kilometers: "kilomètres", byStatus: "Répartition par statut", byAgency: "Missions par agence", agencyDetail: "Détail par agence", agency: "Agence", total: "Total", rate: "Taux", noData: "Aucune donnée" },
    roles: { super_admin: "Super Admin", csa: "CSA", dsa: "DSA", fsco: "FSCO", fsa: "FSA", assistant_soc: "Assistant SOC", undefined: "Non défini" },
    criticality: { PC1: "PC1 - Critique", PC2: "PC2 - Haute", PC3: "PC3 - Moyenne", PC4: "PC4 - Basse" },
    transport: { road: "Routier", air: "Aérien", both: "Mixte" },
    status: { planned: "Planifiée", in_progress: "En cours", completed: "Terminée", cancelled: "Annulée" },
    errors: { generic: "Une erreur s'est produite", unauthorized: "Non autorisé", notFound: "Non trouvé", required: "Ce champ est requis" },
    success: { saved: "Enregistré avec succès", created: "Créé avec succès", updated: "Mis à jour avec succès", deleted: "Supprimé avec succès", profileCreated: "Profil créé", profileUpdated: "Profil mis à jour", profileDeleted: "Profil supprimé" },
    accessDenied: { title: "Accès non autorisé", contactAdmin: "Veuillez contacter votre CSA ou DSA pour l'attribution de vos zones SRM.", accountCreated: "Votre compte a été créé mais aucune zone SRM ne vous a encore été attribuée. L'accès à l'application sera activé une fois vos zones assignées.", contactZoneManager: "Contactez votre responsable de zone", logout: "Se déconnecter", welcomeTitle: "Bienvenue !", selectCountry: "Sélectionnez votre pays d'affectation pour continuer", chooseCountry: "Choisir un pays", afterSelection: "Après votre sélection, les administrateurs de ce pays seront notifiés et pourront activer votre compte.", sendRequest: "Envoyer la demande", requestSubmitted: "Demande envoyée", adminNotified: "Les administrateurs ont été notifiés de votre demande. Vous recevrez un email lorsque votre compte sera activé.", selectedCountry: "Pays sélectionné", newUserRequest: "Nouvelle demande d'activation", newUserMessage: "{name} demande l'activation pour le pays: {country}", requestSent: "Demande envoyée avec succès" }
  }
};

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem("app_language");
    return saved || "en";
  });

  useEffect(() => {
    localStorage.setItem("app_language", language);
  }, [language]);

  const t = (key, params = {}) => {
    const keys = key.split(".");
    let value = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    if (!value) {
      console.warn(`Translation missing for key: ${key}`);
      return key;
    }
    
    let result = value;
    Object.keys(params).forEach(param => {
      result = result.replace(new RegExp(`{${param}}`, 'g'), params[param]);
    });
    
    return result;
  };

  const changeLanguage = (lang) => {
    if (translations[lang]) {
      setLanguage(lang);
    }
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};